### ISSUE TITLE
package naming

### ISSUE THREAD

**Issue by fredbi** [casualjim/go-httpd#1]
We should respect the de facto norm with directory = package name, even though this is not strictly enforced by the compiler (cf. other known issues with goimports, ...).

I suggest: `go-httpd/httpd`

**Comment by casualjim** [comment]
it's fine, tools know about the go- prefix, it's a common used pattern
Otherwise I have to come up with another name because httpd already has a very famous meaning

**Comment by fredbi** [comment]
Ok thks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
